#!/usr/bin/env python3
"""Give a finite number of hearts to Not quiet a dog. Python standard library only."""

import argparse
import json
import math
import secrets
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

# Public browser configuration from the site's JavaScript, not an admin key.
API = "https://caytaxksqrhrdvontdca.supabase.co/rest/v1"
KEY = "sb_publishable_7lKXZ7SPyRBR0uSNUqbt1g_qJlg_cY1"
CAT_ID = "3be94441-c4e0-4445-8685-e29dcbe04045"
CAT_NAME = "Not quiet a dog"


def request(path, body=None):
    data = None if body is None else json.dumps(body).encode()
    req = Request(API + path, data=data, headers={
        "apikey": KEY,
        "Content-Type": "application/json",
    })
    try:
        with urlopen(req, timeout=20) as response:
            return json.load(response)
    except HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:500]
        raise RuntimeError(f"HTTP {exc.code}: {detail}") from exc
    except (URLError, TimeoutError, ValueError) as exc:
        # Do not retry: a timed-out vote may already have been counted.
        raise RuntimeError(f"Request failed; not retried: {exc}") from exc


def run(count, delay, dry_run, workers=1):
    query = urlencode({"select": "id,name,hearts", "id": f"eq.{CAT_ID}",
                       "status": "eq.approved"})
    dogs = request("/dogs?" + query)
    if len(dogs) != 1 or dogs[0]["name"] != CAT_NAME:
        raise RuntimeError("The expected cat entry is missing or renamed; stopping.")
    print(f'{CAT_NAME}: {dogs[0]["hearts"]} hearts currently.', flush=True)
    if dry_run:
        print(f"Dry run: would submit {count} hearts across {workers} workers, "
              f"with {delay}s between each worker's votes.")
        return

    confirmed = 0
    claimed = 0
    lock = threading.Lock()
    stop = threading.Event()

    def worker():
        nonlocal confirmed, claimed
        device = None
        left = 0
        try:
            while not stop.is_set():
                with lock:
                    if stop.is_set() or claimed >= count:
                        return
                    claimed += 1
                if left == 0:
                # Same 18-byte random device identifier generated by a fresh browser.
                    device = secrets.token_urlsafe(18)
                    status = request("/rpc/heart_status", {"p_device": device})
                    if status.get("open") is not True:
                        raise RuntimeError("Voting is paused or closed.")
                    left = status.get("left")
                    if not isinstance(left, int) or left <= 0:
                        raise RuntimeError(f"Unexpected fresh-device allowance: {status}")
                if stop.is_set():
                    return
                result = request("/rpc/give_heart", {"p_device": device, "p_dog": CAT_ID})
                if result.get("ok") is not True:
                    raise RuntimeError(f"Vote rejected; stopping: {result}")
                with lock:
                    confirmed += 1
                    print(f'{confirmed}/{count} confirmed; observed cat total: '
                          f'{result.get("hearts", "?")}', flush=True)
                left = result.get("left")
                if not isinstance(left, int) or left < 0:
                    raise RuntimeError(f"Unexpected remaining allowance: {result}")
                with lock:
                    if claimed >= count:
                        return
                if delay > 0 and stop.wait(delay):
                    return
        except Exception:
            stop.set()
            raise

    pool = ThreadPoolExecutor(max_workers=workers)
    try:
        futures = [pool.submit(worker) for _ in range(min(workers, count))]
        for future in as_completed(futures):
            future.result()
    finally:
        stop.set()
        # Already-sent requests may finish after an error or Ctrl+C.
        pool.shutdown(wait=True, cancel_futures=True)
        print(f"Confirmed {confirmed} of {count} requested hearts.", flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hearts", type=int, default=100, help="total hearts (default: 100)")
    parser.add_argument("--delay", type=float, default=0.0,
                        help="seconds between votes per worker, 0–60; 0 disables waiting (default: 0)")
    parser.add_argument("--workers", type=int, default=1,
                        help="parallel sessions, 1–4 (default: 1)")
    parser.add_argument("--dry-run", action="store_true", help="verify the cat without voting")
    args = parser.parse_args()
    if args.hearts <= 0:
        parser.error("--hearts must be positive")
    if not math.isfinite(args.delay) or not 0 <= args.delay <= 60:
        parser.error("--delay must be between 0 and 60 seconds")
    if not 1 <= args.workers <= 4:
        parser.error("--workers must be between 1 and 4")
    try:
        run(args.hearts, args.delay, args.dry_run, args.workers)
    except (RuntimeError, OSError) as exc:
        print(f"Stopped: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Stopped by user.", file=sys.stderr)
        return 130
    return 0


if __name__ == "__main__":
    sys.exit(main())
